name: CI
on:
  push:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1
      - run: moon fmt
      - run: moon check --target wasm-gc --deny-warn
      - run: moon check --target wasm --deny-warn
      - run: moon check --target js --deny-warn
      - run: moon check --target native --deny-warn
      - run: moon test --target wasm-gc --deny-warn


